version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 5
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 5
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      filecoin:
        patterns:
          - "filecoin-pin"
          - "@filoz/*"
      all-other-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "filecoin-pin"
          - "@filoz/*"
    ignore:
      - dependency-name: "@biomejs/biome"
        update-types: ["version-update:semver-patch"]
