name: Auto-label issues and PRs

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/github-script@v7
        with:
          # Use PAT instead of default GITHUB_TOKEN to trigger subsequent workflows.
          # Events triggered by GITHUB_TOKEN do not create new workflow runs by design.
          # This allows the add-issues-and-prs-to-fs-project-board.yml workflow to be triggered when labels are added.
          # See: https://docs.github.com/en/actions/concepts/security/github_token
          github-token: ${{ secrets.FILOZZY_CI_ADD_TO_PROJECT }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['team/fs-wg', 'team/filecoin-pin']
            })